CREATE TABLE MEMBER (
    USER_ID VARCHAR2(30) PRIMARY KEY,
    USER_PW VARCHAR2(65) NOT NULL,
    POINT NUMBER(10) DEFAULT 100,
    REG_DT DATE DEFAULT SYSDATE,
    MOD_DT DATE
);

CREATE TABLE POINT_LOG (
    SEQ NUMBER(10) PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL,
    POINT NUMBER(10),
    REG_DT DATE DEFAULT SYSDATE
);


SELECT SUM(POINT) FROM POINT_LOG WHERE USER_ID=''


UPDATE MEMBER SET POINT=... WHERE USER_ID='...'